<?php if ( ! defined( 'ABSPATH' ) ) exit; ?>
<?php
global $wpdb;
$table_wow_signup = $wpdb->prefix . "wow_signup";
$wowpage = 'wow-viral-signups-pro';
$act = (isset($_REQUEST["act"])) ? $_REQUEST["act"] : '';
if ($act == "update") { 
$recid = $_REQUEST["id"];
$result = $wpdb->get_row("SELECT * FROM $table_wow_signup WHERE id=$recid");
    if ($result){
        $id = $result->id;
        $title = $result->title;
		$type_signup = $result->type_signup;
		$number_invites = $result->number_invites;
		$number_taken = $result->number_taken;
		$first_text = $result->first_text;
		$second_text = $result->second_text;
		$confirmation_text = $result->confirmation_text;
		$button_text = $result->button_text;
		$share_text = $result->share_text;
		$twitter_text = $result->twitter_text;
		$share_link = $result->share_link;
		$specify_anchor = $result->specify_anchor;
		$referrals = $result->referrals;
		$block_user = $result->block_user;
		$directly = $result->directly;
		$custom_share_text = $result->custom_share_text;
		$facebook_share_text = $result->facebook_share_text;
		$fb_app_id = $result->fb_app_id;
		$position = $result->position;
		$alignment = $result->alignment;
		$first_text_size = $result->first_text_size;
		$second_text_size = $result->second_text_size;
		$link_size = $result->link_size;
		$confirmation_first_size = $result->confirmation_first_size;
		$confirmation_second_size = $result->confirmation_second_size;
		$confirmation_text_size = $result->confirmation_text_size;
		$button_text_size = $result->button_text_size;
		$first_text_color = $result->first_text_color;
		$second_text_color = $result->second_text_color;
		$confirmation_first_text_color = $result->confirmation_first_text_color;
		$confirmation_second_text_color = $result->confirmation_second_text_color;
		$confirmation_text_color = $result->confirmation_text_color;
		$button_text_color = $result->button_text_color;
		$button_color = $result->button_color;
		$button_hover_color = $result->button_hover_color;
		$button_disabled_color = $result->button_disabled_color;
		$placeholder_text = $result->placeholder_text;
		$integration = $result->integration;
		$choosservice = $result->choosservice;
		$mailchimp_api = $result->mailchimp_api;
		$mailchimp_list = $result->mailchimp_list;
		$getresponse_api = $result->getresponse_api;
		$getresponse_list = $result->getresponse_list;
		$btn = __("Update", "wow-marketings");
        $hidval = 2;
    }
}
else if ($act == "duplicate") { 
$recid = $_REQUEST["id"];
$result = $wpdb->get_row("SELECT * FROM $table_wow_signup WHERE id=$recid");
   if ($result){   
        $id = "";
        $title = "";
		$type_signup = $result->type_signup;
		$number_invites = $result->number_invites;
		$number_taken = $result->number_taken;
		$first_text = $result->first_text;
		$second_text = $result->second_text;
		$confirmation_text = $result->confirmation_text;
		$button_text = $result->button_text;
		$share_text = $result->share_text;
		$twitter_text = $result->twitter_text;
		$share_link = $result->share_link;
		$specify_anchor = $result->specify_anchor;
		$referrals = $result->referrals;
		$block_user = $result->block_user;
		$directly = $result->directly;
		$custom_share_text = $result->custom_share_text;
		$facebook_share_text = $result->facebook_share_text;
		$fb_app_id = $result->fb_app_id;
		$position = $result->position;
		$alignment = $result->alignment;
		$first_text_size = $result->first_text_size;
		$second_text_size = $result->second_text_size;
		$link_size = $result->link_size;
		$confirmation_first_size = $result->confirmation_first_size;
		$confirmation_second_size = $result->confirmation_second_size;
		$confirmation_text_size = $result->confirmation_text_size;
		$button_text_size = $result->button_text_size;
		$first_text_color = $result->first_text_color;
		$second_text_color = $result->second_text_color;
		$confirmation_first_text_color = $result->confirmation_first_text_color;
		$confirmation_second_text_color = $result->confirmation_second_text_color;
		$confirmation_text_color = $result->confirmation_text_color;
		$button_text_color = $result->button_text_color;
		$button_color = $result->button_color;
		$button_hover_color = $result->button_hover_color;
		$button_disabled_color = $result->button_disabled_color;
		$placeholder_text = $result->placeholder_text;
		$integration = $result->integration;
		$choosservice = $result->choosservice;
		$mailchimp_api = $result->mailchimp_api;
		$mailchimp_list = $result->mailchimp_list;
		$getresponse_api = $result->getresponse_api;
		$getresponse_list = $result->getresponse_list;
		$btn = __("Save", "wow-marketings");
        $hidval = 1;
    }
}
 else {
    $btn = __("Save", "wow-marketings");
    $id = "";
    $title = "";
	$type_signup = "";
	$number_invites = "1000";
	$number_taken = "300";
	$first_text = "invites available";
	$second_text = "out of";
	$confirmation_text = "Thank you for signing up";
	$button_text = "Submit";
	$share_text = "Guess what? Great news! We will give away a lifetime premium account to those who bring 3 friends to sign up!";
	$twitter_text = "Check out awesome wordpress plugins by DayesDesign at http://marketing-wp.com/";
	$share_link = "http://";
	$specify_anchor = "";
	$referrals = "3";
	$block_user = "30";
	$directly = "1";
	$custom_share_text = "";
	$facebook_share_text = "Check out awesome wordpress plugins by DayesDesign at http://marketing-wp.com/";
	$fb_app_id = "";
	$position = "";
	$alignment = "";
	$first_text_size = "";
	$second_text_size = "";
	$link_size = "";
	$confirmation_first_size = "";
	$confirmation_second_size = "";
	$confirmation_text_size = "";
	$button_text_size = "";
	$first_text_color = "";
	$second_text_color = "";
	$confirmation_first_text_color = "";
	$confirmation_second_text_color = "";
	$confirmation_text_color = "";
	$button_text_color = "";
	$button_color = "";
	$button_hover_color = "";
	$button_disabled_color = "";
	$placeholder_text = "Type your email...";
	$integration = "";
	$choosservice = "";
	$mailchimp_api = "";
	$mailchimp_list = "";
	$getresponse_api = "";
	$getresponse_list = "";
    $hidval = 1;
}
?>