.signup-<?php echo $val->id; ?> p { font-size: <?php if(empty($val->second_text_size )){echo "24";}else{echo $val->second_text_size;}?>px; color: <?php if(empty($val->second_text_color )){echo "#4e4e4e";}else{echo $val->second_text_color;}?>; }
.signup-<?php echo $val->id; ?> span { font-size: <?php if(empty($val->first_text_size )){echo "24";}else{echo $val->first_text_size;}?>px; color: <?php if(empty($val->first_text_color )){echo "#58c486";}else{echo $val->first_text_color;}?>; }
.signup-<?php echo $val->id; ?> .success .limitedtext p { font-size: <?php if(empty($val->confirmation_second_size )){echo "24";}else{echo $val->confirmation_second_size;}?>px; color: <?php if(empty($val->confirmation_second_text_color )){echo "#58c486";}else{echo $val->confirmation_second_text_color;}?>; }
.signup-<?php echo $val->id; ?> .success .limitedtext span {  font-size: <?php if(empty($val->confirmation_first_size )){echo "24";}else{echo $val->confirmation_first_size;}?>px; color: <?php if(empty($val->confirmation_first_text_color )){echo "#58c486";}else{echo $val->confirmation_first_text_color;}?>; }
.signup-<?php echo $val->id; ?> .success p { font-size: <?php if(empty($val->confirmation_text_size )){echo "16";}else{echo $val->confirmation_text_size;}?>px; color: <?php if(empty($val->confirmation_text_color )){echo "#4e4e4e";}else{echo $val->confirmation_text_color;}?>; }
.signup-<?php echo $val->id; ?> button { font-size: <?php if(empty($val->button_text_size )){echo "16";}else{echo $val->button_text_size;}?>px; color:<?php if(empty($val->button_text_color )){echo "#ffffff";}else{echo $val->button_text_color;}?>; background: <?php if(empty($val->button_color )){echo "#58c486";}else{echo $val->button_color;}?>; }
.signup-<?php echo $val->id; ?> button:hover { background:<?php if(empty($val->button_hover_color )){echo "#51b77c";}else{echo $val->button_hover_color;}?>; cursor:pointer}
.signup-<?php echo $val->id; ?> button:disabled { background:<?php if(empty($val->button_disabled_color )){echo "#e5e5e5";}else{echo $val->button_disabled_color;}?>; cursor: default; text-align: 2; }
.signup-<?php echo $val->id; ?> { <?php if($val->position== 2){echo 'margin: 0 auto;';} if($val->position== 3){echo 'margin-left: auto;';} if($val->position== 1 || $val->position== "") {echo 'margin: 0;';}; ?>; text-align: <?php if(empty($val->alignment )){echo "left";}else{echo $val->alignment;}?>; }
#yourlink-<?php echo $val->id; ?> {font-size: <?php if(empty($val->link_size )){echo "12";}else{echo $val->link_size;}?>px;} 